### ISSUE TITLE
Webinterface is a white page with some links after installing

### ISSUE THREAD

**Issue by sizilianos** [andreknieriem/photobooth#307]
Hi,
i installed the file as in the wiki documentation on a Raspberry pi. But after starting the Webinterface I see only a white page with some links like.

Photobooth

Webinterface by André Rinas

[ Foto erstellen!](http://192.168.178.36/#)
[Fork me on GitHub](https://github.com/andreknieriem/photobooth)
[None](http://192.168.178.36/#)
[Antique](http://192.168.178.36/#)
[Aqua](http://192.168.178.36/#)
[Blue](http://192.168.178.36/#)
[Blur](http://192.168.178.36/#)

Is this a bug or do I have done something wrong?

**Comment by andi34** [comment]
Sounds like `yarn build` didn't run and missing the css files because of that. Please note the installer is made for Debian buster based distributions, on bullseye there might be issues.

PiOS with Desktop and pre-installed Photobooth v3 of my fork https://github.com/andi34/photobooth:

https://drive.google.com/drive/folders/1ziXOr46wZ_vdv9jQ0D3Wb8XHLEBek0Vl

PiOS Login:
User: photobooth
Password: photobooth

**Comment by andi34** [comment]
There might be a tiny bug by chromium after first Login. Once the welcome message of Photobooth is skipped the browser might stay white,  after a reboot everything should be fine.
Photobooth will start in Kiosk-Mode automatically.

**Comment by sizilianos** [comment]
Thank you! It works now.

**Comment by andi34** [comment]
Good to hear! Enjoy the Photobooth! More to come in the works 😊

**Comment by sizilianos** [comment]
Next totally noob question:
"PiOS with Desktop and pre-installed Photobooth v3 of my fork"

I could use the raspberry pi with a normal monitor to see the screen with a browser?

**Comment by andi34** [comment]
Yes, that's what most people do on finished boxes because accessing Photobooth via IP-Adress has limitations on the preview options if needed.

An custom Ubuntu x64 build for other hardware will also be available soon. (E.g. if preview from gphoto2 is used a raspberry reaches his performance edges while it works fluid on better hardware. Also if collage or chroma keying is used, the performance is much better on better hardware).

**Comment by andi34** [comment]
Feel free to join us at telegram to stay informed and getting support and ideas from other Photobooth user https://t.me/PhotoboothGroup
